version: "3"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: kinoteka_api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "admin" ]
    ports:
      - 5432:5432

  migrate:
    image: migrate:1
    environment:
      PGDATABASE: kinoteka_api
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: db
      PGPORT: 5432
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  backend:
    image: backend:1
    restart: always
    environment:
      PG_NAME: kinoteka_api
      PG_USER: admin
      PG_PASSWORD: admin
      PG_HOST: db
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy